### ISSUE TITLE
Does not download driver for Edge Chromium

### ISSUE THREAD

**Issue by schneidly** [rasjani/webdrivermanager#26]
This fails to download the drivers for MS Edge Chromium.  Works great for Chrome, Firefox and Edge(HTML) .  Unfortunately Microsoft no longer supports Edge(HTML).  Are you planning to update or should I pull the source and do it myself?

**Comment by rasjani** [comment]
Hiya!

Main reason why i havent really gotten to implement Edge chromium download is that i mainly use Robot Framework for webtesting with SeleniumLibrary (which depends on python Selenium) and AFAIK there is no official support yet for Edge Chromium on that side yet.

However, i wouldn't mind patches as WDM is definitely more generic than just RF & SL.

I think the binary locations and list of releases for Edge Chromium releases can be fetches from:

https://msedgewebdriverstorage.blob.core.windows.net/edgewebdriver?maxresults=1000&comp=list&timeout=60000

**Comment by schneidly** [comment]
Jani,

I will be happy to help you out.  Ideally since you are currently stuck
with Edge HTML version I will implement it with a switch so that it will
not effect your work.

Regards,

Thomas

**Comment by rasjani** [comment]
If you know how to install or use wdm directory from github, there's a branch now called "edge-chromium" that works at least when downloading mac edge webdriver.. If you could test it and see if you spot any issues, that would be really helpfull ;)

**Comment by schneidly** [comment]
Jani,


Got it and will look  into it as time permits.


Thanks,

Thomas
