### ISSUE TITLE
Update and Remove function

### ISSUE THREAD

**Issue by bes1002t** [rasjani/webdrivermanager#36]
Two questions:

1. Is it possible to somehow remove the downloaded driver?
2. Is it possible to update the downloaded driver without removing it?

Currently I have the same issue as described in #35 , so I try to workaround until a new release is available in pip.

**Comment by rasjani** [comment]
1.  There's no mechanism to remove the downloaded driver. Personally I run things always inside virtually env which can be cleaned up (eg. Removing the downloaded version is side effect)
2. If you run wdm, previous versions are kept in old location but the new binary should be symlinked (linux/Mac - copyed over on windows) over the previous one. 

Btw, sorry for taking time to release the fix.   Been too busy at work and I don't really need webdrives there.. but 0.9.0 is now in pypi.

**Comment by bes1002t** [comment]
no problem, thanks for clarification :)
