### ISSUE TITLE
EdgeChromiumDriverManager().download_and_install() failed

### ISSUE THREAD

**Issue by MrBIN89** [rasjani/webdrivermanager#39]
```
Python 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 24 2018, 00:16:47) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from webdrivermanager import EdgeChromiumDriverManager
>>> EdgeChromiumDriverManager().download_and_install()
Error, unable to find appropriate download for win64.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "d:\TIFF\python_envs\drivermngr\lib\site-packages\webdrivermanager\webdrivermanager.py", line 266, in download_and_install
    filename_with_path = self.download(version, show_progress_bar=show_progress_bar)
  File "d:\TIFF\python_envs\drivermngr\lib\site-packages\webdrivermanager\webdrivermanager.py", line 222, in download
    (download_url, filename) = self.get_download_url(version)
  File "d:\TIFF\python_envs\drivermngr\lib\site-packages\webdrivermanager\webdrivermanager.py", line 695, in get_download_url
    raise_runtime_error('Error, unable to find appropriate download for {0}{1}.'.format(self.os_name, self.bitness))
  File "d:\TIFF\python_envs\drivermngr\lib\site-packages\webdrivermanager\webdrivermanager.py", line 34, in raise_runtime_error
    raise RuntimeError(msg)
RuntimeError: Error, unable to find appropriate download for win64.
```

After a quick look:
* It tries to find `/82.0.456.0/edgedriver_win64` and fails, due to this version has only arm64.zip
* Seems like it doesn't detect actual latest Edge Chromium version.
The 87th exists already according to https://developer.microsoft.com/ru-ru/microsoft-edge/tools/webdriver/ 

Versions:
* webdrivermanager 0.9.0
* Python 3.6.8
* Windows 10 (x64)

**Comment by rasjani** [comment]
Looks like issue is they changed the html structure a bit  and scraping with beautifulsoup fails because of unexpected changes. Ill take a look

**Comment by rasjani** [comment]
So the actual issue is that "LATEST" is arm64 only, and logic without providing the exact version is to fetch the latest, which than fails because only arm64 of the highest version is available.  

I'll think of something to workaround this for now but this sort of falls into my refactoring efforts also a bit later on..

**Comment by MrBIN89** [comment]
Good news! 
Yeah, actually this bug report points to two thing, the first one - missed os&bitness package for some version, and another one - changes in html or might be in address (doesn't find real latest version for edgechromium driver).
Wait eagerly for both fixed.
