### ISSUE TITLE
Chromedriver version installed

### ISSUE THREAD

**Issue by davidwickerhf** [rasjani/webdrivermanager#54]
First of all, I wanted to thank @rasjani for this great project that saved my life countless times already!
I am encountering a small issue when the driver is being installed: 
is there a way to tell the WebDriverManager to check for a local Chrome version before installing the appropriate chrome driver?
I apologize if this question has already been asked/answered...
Thank you,
David

**Comment by rasjani** [comment]
Yes there is. But  Its not documented for a reason as i wanted to get possible bug reports before people go nuts about it.  Its not implemented for all browsers.  Ill leave longer comment and document it a bit later

**Comment by davidwickerhf** [comment]
Alright! Thank you for that
I'll check through the code if I can find a way to set it that way and if there are any issues I'll  get back to you

**Comment by rasjani** [comment]
if version is defined as "compatible", it should try to probe the browser version ;)

**Comment by davidwickerhf** [comment]
@rasjani sorry, is this test feature included in the pip download or should I install the package by cloning the repo with the new commits?
Thank you and sorry for the redundant question

**Comment by rasjani** [comment]
As said on earlier reply: "it came in the latest Release".. eg 0.10.0. https://pypi.org/project/webdrivermanager/0.10.0/
